# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

secondary_prompt:
    template: '❯❯ '
    foreground: magenta
    background: transparent
transient_prompt:
    template: '❯ '
    background: transparent
    foreground_templates:
        - '{{ if gt .Code 0 }}red{{ end }}'
        - '{{ if eq .Code 0 }}magenta{{ end }}'
console_title_template: '{{ .Shell }} in {{ .Folder }}'
blocks:
    - type: prompt
      alignment: left
      segments:
        - template: '{{ if .SSHSession }}  {{ .UserName }}@{{ .HostName }}{{ end }}'
          foreground: blue
          background: transparent
          type: session
          style: plain
        - foreground: blue
          background: transparent
          type: path
          style: plain
          properties:
            style: full
        - template: ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
          foreground: p:grey
          background: transparent
          type: git
          style: plain
          properties:
            branch_icon: ''
            commit_icon: '@'
            fetch_status: true
      newline: true
    - type: rprompt
      overflow: hidden
      segments:
        - template: '{{ .FormattedMs }}'
          foreground: yellow
          background: transparent
          type: executiontime
          style: plain
    - type: prompt
      alignment: left
      segments:
        - template: ❯
          background: transparent
          type: text
          style: plain
          foreground_templates:
            - '{{ if gt .Code 0 }}red{{ end }}'
            - '{{ if eq .Code 0 }}magenta{{ end }}'
      newline: true
version: 4
final_space: true
